
/**************************************************************
 *	
 *	Blink, 8 bit, 11025Hz,
 *	1 channel, 30466 bytes/channel
 *	Total Size: 1 * 30466 + 4 (header) = 30510 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/enya/Desktop/2261/finalProject2/sounds/Blink.wav
 *	Time-stamp: Tue Apr 04 22:19:48 2017
 *	
 **************************************************************/

#ifndef __BLINKH__
#define __BLINKH__

#define BLINKFREQ 11025
#define BLINKLEN 30466

extern const unsigned char Blink[30466];

#endif /* __BLINKH__ */
