
/**************************************************************
 *	
 *	crack, 8 bit, 11025Hz,
 *	1 channel, 14609 bytes/channel
 *	Total Size: 1 * 14609 + 4 (header) = 14653 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/enya/Desktop/finalProject3New/sounds/crack.wav
 *	Time-stamp: Mon Apr 24 21:28:23 2017
 *	
 **************************************************************/

#ifndef __CRACKH__
#define __CRACKH__

#define CRACKFREQ 11025
#define CRACKLEN 14609

extern const unsigned char crack[14609];

#endif /* __CRACKH__ */
