
/**************************************************************
 *	
 *	Rain, 8 bit, 11025Hz,
 *	1 channel, 256123 bytes/channel
 *	Total Size: 1 * 256123 + 4 (header) = 256167 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/enya/Desktop/2261/finalProject2/sounds/Rain.wav
 *	Time-stamp: Tue Apr 04 14:02:47 2017
 *	
 **************************************************************/

#ifndef __RAINH__
#define __RAINH__

#define RAINFREQ 11025
#define RAINLEN 250000

extern const unsigned char Rain[256123];

#endif /* __RAINH__ */
