
/**************************************************************
 *	
 *	ticking, 8 bit, 11025Hz,
 *	1 channel, 1531 bytes/channel
 *	Total Size: 1 * 1531 + 4 (header) = 1575 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/enya/Desktop/finalProject3New/sounds/ticking.wav
 *	Time-stamp: Mon Apr 24 17:36:49 2017
 *	
 **************************************************************/

#ifndef __TICKINGH__
#define __TICKINGH__

#define TICKINGFREQ 11025
#define TICKINGLEN 1200

extern const unsigned char ticking[1531];

#endif /* __TICKINGH__ */
