
/**************************************************************
 *	
 *	Umbrella, 8 bit, 11025Hz,
 *	1 channel, 4301 bytes/channel
 *	Total Size: 1 * 4301 + 4 (header) = 4345 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/enya/Desktop/2261/finalProject2/sounds/Umbrella.wav
 *	Time-stamp: Mon Apr 03 16:55:05 2017
 *	
 **************************************************************/

#ifndef __UMBRELLAH__
#define __UMBRELLAH__

#define UMBRELLAFREQ 11025
#define UMBRELLALEN 4200

extern const unsigned char Umbrella[4301];

#endif /* __UMBRELLAH__ */
