
/**************************************************************
 *	
 *	Rain, 8 bit, 11025Hz,
 *	1 channel, 253810 bytes/channel
 *	Total Size: 1 * 253810 + 4 (header) = 253854 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/enya/Desktop/2261/finalProject2/sounds/Rain.wav
 *	Time-stamp: Tue Apr 04 20:01:35 2017
 *	
 **************************************************************/

#ifndef __RAINH__
#define __RAINH__

#define RAINFREQ 11025
#define RAINLEN 253810

extern const unsigned char Rain[253810];

#endif /* __RAINH__ */
